metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  create-environment:
    envs:
    - host
    path: pipelines/create-environment
    stages:
    - build-docker-image
    - launch-services
  prepare-music-data:
    envs:
    - host
    path: pipelines/prepare-music-data
    stages:
    - prepare-musdb
    - generate-dataset
    - move-dataset
  rnn-music-baseline:
    envs:
    - host
    path: pipelines/rnn-music-baseline
    stages:
    - train
    - separate
    - evaluate
popperized:
- github/popperized
