metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  create-docker-environment:
    envs:
      host:
        args: []
    path: pipelines/create-docker-environment
    stages:
    - build-docker-image
    - launch-services
  create-anaconda-environment:
    envs:
      host:
        args: []
    path: pipelines/create-anaconda-environment
    stages:
    - build-conda-env
    - launch-services
  prepare-music-data:
    envs:
      host:
        args: []
    path: pipelines/prepare-music-data
    stages:
    - prepare-musdb
    - generate-dataset
    - move-dataset
  rnn-music-baseline:
    envs:
      host:
        args: []
    path: pipelines/rnn-music-baseline
    stages:
    - train
    - separate
    - evaluate
  em-cluster-music:
    envs:
      host:
        args: []
    path: pipelines/em-cluster-music
    stages:
    - train
    - separate
    - evaluate
popperized:
- github/popperized
