metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  docker-data-science:
    envs:
    - host
    path: pipelines/create-environment
    stages:
    - build-docker-image
    - launch-services
  prepare-data:
    envs:
    - host
    path: pipelines/prepare-data
    stages:
    - setup
    - run
    - post-run
    - validate
    - teardown
popperized:
- github/popperized
