metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  create-environment:
    envs:
    - host
    path: pipelines/create-environment
    stages:
    - build-docker-image
    - launch-services
  prepare-data:
    envs:
    - host
    path: pipelines/prepare-data
    stages:
    - prepare-musdb
popperized:
- github/popperized
